//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation

class ___VARIABLE_sceneName___Interactor {
    
    // MARK: Delegate initialization
    var presenter: ___VARIABLE_sceneName___InterectorToPresenterProtocol?
    
    // MARK: - Call Service
    
}

// MARK: - Presenter to Interactor
extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___PresentorToInterectorProtocol {
    
}
