//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

class ___VARIABLE_sceneName___Presenter {
    
    // MARK: - Private properties
    private unowned var view: ___VARIABLE_sceneName___PresenterToViewProtocl
    private var interactor: ___VARIABLE_sceneName___PresentorToInterectorProtocol
    private var router: ___VARIABLE_sceneName___PresenterToRouterProtocol
    
    // MARK: - Lifecycle
    init(view: ___VARIABLE_sceneName___PresenterToViewProtocl, interactor: ___VARIABLE_sceneName___PresentorToInterectorProtocol, router: ___VARIABLE_sceneName___PresenterToRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    
}

// MARK: - View to Presenter
extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___ViewToPresenterProtocol {
    
    func started() {
        view.initialControlSetup()
    }
    
}

// MARK: - Interactor to Presenter
extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___InterectorToPresenterProtocol {
    
}

