//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import UIKit
import Foundation

class ___VARIABLE_sceneName___Router: BaseRouter {
    
    // MARK: - Private properties
    private let storyboard = UIStoryboard(name: "___VARIABLE_sceneName___", bundle: nil)
    
    // MARK: Module Setup
    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: ___VARIABLE_sceneName___ViewController.self)
        super.init(viewController: moduleViewController)
        let interactor = ___VARIABLE_sceneName___Interactor()
        let presenter = ___VARIABLE_sceneName___Presenter(view: moduleViewController, interactor: interactor, router: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }
    
}

// MARK: - Presenter to Wireframe Interface
extension ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___PresenterToRouterProtocol {
    
    func navigate(to option: ___VARIABLE_sceneName___NavigationOption) {
        // ...
    }
    
}
