//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Zin Lin Htet Naing.
//

import Foundation
import UIKit

// MARK: - Navigation Option
enum ___VARIABLE_sceneName___NavigationOption {
    /**
     - example usage
     */
}

// MARK: - Presenter -> View
protocol ___VARIABLE_sceneName___PresenterToViewProtocl: BaseViewProtocol {
    func initialControlSetup()
}

// MARK: - View -> Presenter
protocol ___VARIABLE_sceneName___ViewToPresenterProtocol: AnyObject {
    func started()
}

// MARK: - Interactor -> Presenter
protocol ___VARIABLE_sceneName___InterectorToPresenterProtocol: AnyObject {
    
}

// MARK: - Presenter -> Interactor
protocol ___VARIABLE_sceneName___PresentorToInterectorProtocol: AnyObject {
    
}

// MARK: - Presenter -> Router or WireFrame
protocol ___VARIABLE_sceneName___PresenterToRouterProtocol: BaseRouterProtocol {
    func navigate(to option: ___VARIABLE_sceneName___NavigationOption)
}


